/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedInputStream;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Akila
 */
public class Playing_interface extends javax.swing.JFrame {

    /**
     * Creates new form Playing_interface
     */
    int currentscore = 0;
    int xMouse, yMouse;

    static int thr_val = 00;

    public Playing_interface() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        Window_Closer();
        SETico();
        customCursor();

        target_pig1.setVisible(false);
        target_pig2.setVisible(false);
        target_pig3.setVisible(false);
        target_pig4.setVisible(false);
        target_pig5.setVisible(false);
        target_pig6.setVisible(false);

        targest_animate();
        countdown();

    }

    void Disp() {
        this.dispose();
        HomePage.lb_thread_stoping_value.setText("1");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_dispo = new javax.swing.JButton();
        lb_gamemode = new javax.swing.JLabel();
        jPanel_background = new javax.swing.JPanel(){
            private Image image;{
                try{

                    ImageIcon ii = new ImageIcon(getClass().getResource("/images/BACKGROUND.png"));
                    image = ii.getImage();
                }catch(Exception e){

                }

            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        lb_bullet = new javax.swing.JLabel();
        target_pig1 = new javax.swing.JPanel(){
            private Image image;{
                try{

                    ImageIcon ii = new ImageIcon(getClass().getResource("/images/pigTRG.png"));
                    image = ii.getImage();
                }catch(Exception e){

                }

            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        btn_trg1 = new javax.swing.JButton();
        target_pig2 = new javax.swing.JPanel(){
            private Image image;{
                try{

                    ImageIcon ii = new ImageIcon(getClass().getResource("/images/pigTRG.png"));
                    image = ii.getImage();
                }catch(Exception e){

                }

            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        btn_trg2 = new javax.swing.JButton();
        target_pig3 = new javax.swing.JPanel(){
            private Image image;{
                try{

                    ImageIcon ii = new ImageIcon(getClass().getResource("/images/pigTRG.png"));
                    image = ii.getImage();
                }catch(Exception e){

                }

            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        btn_trg3 = new javax.swing.JButton();
        target_pig4 = new javax.swing.JPanel(){
            private Image image;{
                try{

                    ImageIcon ii = new ImageIcon(getClass().getResource("/images/pigTRG.png"));
                    image = ii.getImage();
                }catch(Exception e){

                }

            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        btn_trg4 = new javax.swing.JButton();
        target_pig5 = new javax.swing.JPanel(){
            private Image image;{
                try{

                    ImageIcon ii = new ImageIcon(getClass().getResource("/images/pigTRG.png"));
                    image = ii.getImage();
                }catch(Exception e){

                }

            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        btn_trg5 = new javax.swing.JButton();
        target_pig6 = new javax.swing.JPanel(){
            private Image image;{
                try{

                    ImageIcon ii = new ImageIcon(getClass().getResource("/images/pigTRG.png"));
                    image = ii.getImage();
                }catch(Exception e){

                }

            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        btn_trg6 = new javax.swing.JButton();
        txt_score = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_time = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lb_ammo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        btn_dispo.setText("jButton1");
        btn_dispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dispoActionPerformed(evt);
            }
        });

        lb_gamemode.setText("game mode here");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pigs Hunt");

        jPanel_background.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_backgroundMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_backgroundMousePressed(evt);
            }
        });

        lb_bullet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_bullet.setText("●");
        lb_bullet.setFocusable(false);
        lb_bullet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        target_pig1.setOpaque(false);

        btn_trg1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));
        btn_trg1.setBorderPainted(false);
        btn_trg1.setContentAreaFilled(false);
        btn_trg1.setFocusPainted(false);
        btn_trg1.setFocusable(false);
        btn_trg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trg1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout target_pig1Layout = new javax.swing.GroupLayout(target_pig1);
        target_pig1.setLayout(target_pig1Layout);
        target_pig1Layout.setHorizontalGroup(
            target_pig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_trg1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        target_pig1Layout.setVerticalGroup(
            target_pig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_trg1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        target_pig2.setOpaque(false);

        btn_trg2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));
        btn_trg2.setBorderPainted(false);
        btn_trg2.setContentAreaFilled(false);
        btn_trg2.setFocusPainted(false);
        btn_trg2.setFocusable(false);
        btn_trg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trg2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout target_pig2Layout = new javax.swing.GroupLayout(target_pig2);
        target_pig2.setLayout(target_pig2Layout);
        target_pig2Layout.setHorizontalGroup(
            target_pig2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_trg2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        target_pig2Layout.setVerticalGroup(
            target_pig2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_trg2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        target_pig3.setOpaque(false);

        btn_trg3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));
        btn_trg3.setBorderPainted(false);
        btn_trg3.setContentAreaFilled(false);
        btn_trg3.setFocusPainted(false);
        btn_trg3.setFocusable(false);
        btn_trg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trg3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout target_pig3Layout = new javax.swing.GroupLayout(target_pig3);
        target_pig3.setLayout(target_pig3Layout);
        target_pig3Layout.setHorizontalGroup(
            target_pig3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_trg3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        target_pig3Layout.setVerticalGroup(
            target_pig3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_trg3, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        target_pig4.setOpaque(false);

        btn_trg4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));
        btn_trg4.setBorderPainted(false);
        btn_trg4.setContentAreaFilled(false);
        btn_trg4.setFocusPainted(false);
        btn_trg4.setFocusable(false);
        btn_trg4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trg4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout target_pig4Layout = new javax.swing.GroupLayout(target_pig4);
        target_pig4.setLayout(target_pig4Layout);
        target_pig4Layout.setHorizontalGroup(
            target_pig4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_trg4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        target_pig4Layout.setVerticalGroup(
            target_pig4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_trg4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        target_pig5.setOpaque(false);

        btn_trg5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));
        btn_trg5.setBorderPainted(false);
        btn_trg5.setContentAreaFilled(false);
        btn_trg5.setFocusPainted(false);
        btn_trg5.setFocusable(false);
        btn_trg5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trg5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout target_pig5Layout = new javax.swing.GroupLayout(target_pig5);
        target_pig5.setLayout(target_pig5Layout);
        target_pig5Layout.setHorizontalGroup(
            target_pig5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_trg5, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        target_pig5Layout.setVerticalGroup(
            target_pig5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_trg5, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        target_pig6.setOpaque(false);

        btn_trg6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));
        btn_trg6.setBorderPainted(false);
        btn_trg6.setContentAreaFilled(false);
        btn_trg6.setFocusPainted(false);
        btn_trg6.setFocusable(false);
        btn_trg6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trg6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout target_pig6Layout = new javax.swing.GroupLayout(target_pig6);
        target_pig6.setLayout(target_pig6Layout);
        target_pig6Layout.setHorizontalGroup(
            target_pig6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_trg6, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        target_pig6Layout.setVerticalGroup(
            target_pig6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_trg6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        txt_score.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_score.setText("0000");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Score :");

        txt_time.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_time.setText("Time Remaining 60");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Ammo :");

        lb_ammo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lb_ammo.setText("00");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pistol.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_backgroundLayout = new javax.swing.GroupLayout(jPanel_background);
        jPanel_background.setLayout(jPanel_backgroundLayout);
        jPanel_backgroundLayout.setHorizontalGroup(
            jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_backgroundLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(target_pig2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(330, 330, 330)
                .addComponent(target_pig4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_backgroundLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_score, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                .addComponent(lb_bullet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_ammo)
                .addGap(130, 130, 130)
                .addComponent(txt_time, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_backgroundLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(target_pig1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214)
                .addComponent(target_pig3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(target_pig5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251)
                .addComponent(target_pig6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel_backgroundLayout.setVerticalGroup(
            jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_backgroundLayout.createSequentialGroup()
                        .addComponent(target_pig3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(target_pig2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_backgroundLayout.createSequentialGroup()
                        .addComponent(target_pig4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)))
                .addGap(11, 11, 11))
            .addGroup(jPanel_backgroundLayout.createSequentialGroup()
                .addGroup(jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txt_score)
                        .addComponent(txt_time)
                        .addComponent(jLabel8)
                        .addComponent(lb_ammo)
                        .addComponent(lb_bullet, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(303, 303, 303)
                .addGroup(jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_backgroundLayout.createSequentialGroup()
                        .addComponent(target_pig1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204))
                    .addGroup(jPanel_backgroundLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(target_pig5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(target_pig6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 191, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_trg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trg1ActionPerformed
        if ("E".equals(lb_gamemode.getText())) {
            currentscore = 10;
        }
        if ("N".equals(lb_gamemode.getText())) {
            currentscore = 15;
        }
        if ("H".equals(lb_gamemode.getText())) {
            currentscore = 30;
        }
        int i = currentscore;
        int k = Integer.valueOf(txt_score.getText());
        int val = i + k;
        txt_score.setText(String.valueOf(val));
        target_pig1.setVisible(false);

        int a = Integer.valueOf(lb_ammo.getText());
        int b = a - 1;
        lb_ammo.setText(String.valueOf(b));

        if (a == 0) {
            lb_ammo.setText("0");
            btn_trg1.setEnabled(false);
            btn_trg2.setEnabled(false);
            btn_trg3.setEnabled(false);
            btn_trg4.setEnabled(false);
            btn_trg5.setEnabled(false);
            btn_trg6.setEnabled(false);
            lb_bullet.setVisible(false);
        }
        int bl = Integer.valueOf(lb_ammo.getText());
        if (bl == 0) {
            click_Empty();

        } else {
            gunclick_sound();
            pig_kill();
        }
    }//GEN-LAST:event_btn_trg1ActionPerformed

    private void jPanel_backgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_backgroundMouseClicked
        int a = Integer.valueOf(lb_ammo.getText());
        int b = a - 1;
        lb_ammo.setText(String.valueOf(b));

        if (a == 0) {
            lb_ammo.setText("0");
            btn_trg1.setEnabled(false);
            btn_trg2.setEnabled(false);
            btn_trg3.setEnabled(false);
            btn_trg4.setEnabled(false);
            btn_trg5.setEnabled(false);
            btn_trg6.setEnabled(false);
            lb_bullet.setVisible(false);
        }
        int bl = Integer.valueOf(lb_ammo.getText());
        if (bl == 0) {
            click_Empty();

        } else {
            gunclick_sound();

        }

    }//GEN-LAST:event_jPanel_backgroundMouseClicked

    private void jPanel_backgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_backgroundMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
        lb_bullet.setLocation(xMouse + 12, yMouse + 10);


    }//GEN-LAST:event_jPanel_backgroundMousePressed

    private void btn_trg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trg2ActionPerformed
        if ("E".equals(lb_gamemode.getText())) {
            currentscore = 10;
        }
        if ("N".equals(lb_gamemode.getText())) {
            currentscore = 15;
        }
        if ("H".equals(lb_gamemode.getText())) {
            currentscore = 30;
        }
        int i = currentscore;
        int k = Integer.valueOf(txt_score.getText());
        int val = i + k;
        txt_score.setText(String.valueOf(val));
        target_pig2.setVisible(false);

        int a = Integer.valueOf(lb_ammo.getText());
        int b = a - 1;
        lb_ammo.setText(String.valueOf(b));

        if (a == 0) {
            lb_ammo.setText("0");
            btn_trg1.setEnabled(false);
            btn_trg2.setEnabled(false);
            btn_trg3.setEnabled(false);
            btn_trg4.setEnabled(false);
            btn_trg5.setEnabled(false);
            btn_trg6.setEnabled(false);
            lb_bullet.setVisible(false);
        }
        int bl = Integer.valueOf(lb_ammo.getText());
        if (bl == 0) {
            click_Empty();
        } else {
            gunclick_sound();
            pig_kill();
        }
    }//GEN-LAST:event_btn_trg2ActionPerformed

    private void btn_trg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trg3ActionPerformed
        if ("E".equals(lb_gamemode.getText())) {
            currentscore = 10;
        }
        if ("N".equals(lb_gamemode.getText())) {
            currentscore = 15;
        }
        if ("H".equals(lb_gamemode.getText())) {
            currentscore = 30;
        }
        int i = currentscore;
        int k = Integer.valueOf(txt_score.getText());
        int val = i + k;
        txt_score.setText(String.valueOf(val));
        target_pig3.setVisible(false);

        int a = Integer.valueOf(lb_ammo.getText());
        int b = a - 1;
        lb_ammo.setText(String.valueOf(b));

        if (a == 0) {
            lb_ammo.setText("0");
            btn_trg1.setEnabled(false);
            btn_trg2.setEnabled(false);
            btn_trg3.setEnabled(false);
            btn_trg4.setEnabled(false);
            btn_trg5.setEnabled(false);
            btn_trg6.setEnabled(false);
            lb_bullet.setVisible(false);
        }
        int bl = Integer.valueOf(lb_ammo.getText());
        if (bl == 0) {
            click_Empty();
        } else {
            gunclick_sound();
            pig_kill();
        }
    }//GEN-LAST:event_btn_trg3ActionPerformed

    private void btn_trg4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trg4ActionPerformed
        if ("E".equals(lb_gamemode.getText())) {
            currentscore = 10;
        }
        if ("N".equals(lb_gamemode.getText())) {
            currentscore = 15;
        }
        if ("H".equals(lb_gamemode.getText())) {
            currentscore = 30;
        }
        int i = currentscore;
        int k = Integer.valueOf(txt_score.getText());
        int val = i + k;
        txt_score.setText(String.valueOf(val));
        target_pig4.setVisible(false);

        int a = Integer.valueOf(lb_ammo.getText());
        int b = a - 1;
        lb_ammo.setText(String.valueOf(b));

        if (a == 0) {
            lb_ammo.setText("0");
            btn_trg1.setEnabled(false);
            btn_trg2.setEnabled(false);
            btn_trg3.setEnabled(false);
            btn_trg4.setEnabled(false);
            btn_trg5.setEnabled(false);
            btn_trg6.setEnabled(false);
            lb_bullet.setVisible(false);
        }
        int bl = Integer.valueOf(lb_ammo.getText());
        if (bl == 0) {
            click_Empty();
        } else {
            gunclick_sound();
            pig_kill();
        }
    }//GEN-LAST:event_btn_trg4ActionPerformed

    private void btn_trg5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trg5ActionPerformed
        if ("E".equals(lb_gamemode.getText())) {
            currentscore = 10;
        }
        if ("N".equals(lb_gamemode.getText())) {
            currentscore = 15;
        }
        if ("H".equals(lb_gamemode.getText())) {
            currentscore = 30;
        }
        int i = currentscore;
        int k = Integer.valueOf(txt_score.getText());
        int val = i + k;
        txt_score.setText(String.valueOf(val));
        target_pig5.setVisible(false);

        int a = Integer.valueOf(lb_ammo.getText());
        int b = a - 1;
        lb_ammo.setText(String.valueOf(b));

        if (a == 0) {
            lb_ammo.setText("0");
            btn_trg1.setEnabled(false);
            btn_trg2.setEnabled(false);
            btn_trg3.setEnabled(false);
            btn_trg4.setEnabled(false);
            btn_trg5.setEnabled(false);
            btn_trg6.setEnabled(false);
            lb_bullet.setVisible(false);
        }
        int bl = Integer.valueOf(lb_ammo.getText());
        if (bl == 0) {
            click_Empty();
        } else {
            gunclick_sound();
            pig_kill();
        }
    }//GEN-LAST:event_btn_trg5ActionPerformed

    private void btn_trg6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trg6ActionPerformed
        if ("E".equals(lb_gamemode.getText())) {
            currentscore = 10;
        }
        if ("N".equals(lb_gamemode.getText())) {
            currentscore = 15;
        }
        if ("H".equals(lb_gamemode.getText())) {
            currentscore = 30;
        }
        int i = currentscore;
        int k = Integer.valueOf(txt_score.getText());
        int val = i + k;
        txt_score.setText(String.valueOf(val));
        target_pig6.setVisible(false);

        int a = Integer.valueOf(lb_ammo.getText());
        int b = a - 1;
        lb_ammo.setText(String.valueOf(b));

        if (a == 0) {
            lb_ammo.setText("0");
            btn_trg1.setEnabled(false);
            btn_trg2.setEnabled(false);
            btn_trg3.setEnabled(false);
            btn_trg4.setEnabled(false);
            btn_trg5.setEnabled(false);
            btn_trg6.setEnabled(false);
            lb_bullet.setVisible(false);
        }
        int bl = Integer.valueOf(lb_ammo.getText());
        if (bl == 0) {
            click_Empty();
        } else {
            gunclick_sound();
            pig_kill();
        }
    }//GEN-LAST:event_btn_trg6ActionPerformed

    private void btn_dispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dispoActionPerformed
        this.dispose();
        HomePage.lb_thread_stoping_value.setText("0");


    }//GEN-LAST:event_btn_dispoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Playing_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Playing_interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_dispo;
    private javax.swing.JButton btn_trg1;
    private javax.swing.JButton btn_trg2;
    private javax.swing.JButton btn_trg3;
    private javax.swing.JButton btn_trg4;
    private javax.swing.JButton btn_trg5;
    private javax.swing.JButton btn_trg6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel_background;
    public static javax.swing.JLabel lb_ammo;
    private javax.swing.JLabel lb_bullet;
    public static javax.swing.JLabel lb_gamemode;
    private javax.swing.JPanel target_pig1;
    private javax.swing.JPanel target_pig2;
    private javax.swing.JPanel target_pig3;
    private javax.swing.JPanel target_pig4;
    private javax.swing.JPanel target_pig5;
    private javax.swing.JPanel target_pig6;
    public static javax.swing.JLabel txt_score;
    private javax.swing.JLabel txt_time;
    // End of variables declaration//GEN-END:variables

    private void targest_animate() {

        new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    for (int i = 0; i < 24; i++) {

                        if (i == 1) {
                            target_pig1.setVisible(true);
                            target_pig2.setVisible(false);
                            target_pig3.setVisible(false);
                            target_pig4.setVisible(false);
                            target_pig5.setVisible(false);
                            target_pig6.setVisible(false);
                        }
                        if (i == 3) {
                            target_pig1.setVisible(false);
                            target_pig2.setVisible(false);
                            target_pig3.setVisible(false);
                            target_pig4.setVisible(false);
                            target_pig5.setVisible(false);
                            target_pig6.setVisible(true);
                        }
                        if (i == 5) {
                            target_pig1.setVisible(false);
                            target_pig2.setVisible(true);
                            target_pig3.setVisible(false);
                            target_pig4.setVisible(false);
                            target_pig5.setVisible(false);
                            target_pig6.setVisible(false);
                        }
                        if (i == 7) {
                            target_pig1.setVisible(false);
                            target_pig2.setVisible(false);
                            target_pig3.setVisible(false);
                            target_pig4.setVisible(true);
                            target_pig5.setVisible(false);
                            target_pig6.setVisible(false);
                        }
                        if (i == 9) {
                            target_pig1.setVisible(false);
                            target_pig2.setVisible(false);
                            target_pig3.setVisible(true);
                            target_pig4.setVisible(false);
                            target_pig5.setVisible(false);
                            target_pig6.setVisible(false);
                        }
                        if (i == 11) {
                            target_pig1.setVisible(false);
                            target_pig2.setVisible(false);
                            target_pig3.setVisible(false);
                            target_pig4.setVisible(false);
                            target_pig5.setVisible(true);
                            target_pig6.setVisible(false);
                        }
                        if (i == 13) {
                            target_pig1.setVisible(true);
                            target_pig2.setVisible(false);
                            target_pig3.setVisible(false);
                            target_pig4.setVisible(false);
                            target_pig5.setVisible(false);
                            target_pig6.setVisible(false);
                        }
                        if (i == 15) {
                            target_pig1.setVisible(false);
                            target_pig2.setVisible(true);
                            target_pig3.setVisible(false);
                            target_pig4.setVisible(false);
                            target_pig5.setVisible(false);
                            target_pig6.setVisible(false);
                        }
                        if (i == 17) {
                            target_pig1.setVisible(false);
                            target_pig2.setVisible(false);
                            target_pig3.setVisible(true);
                            target_pig4.setVisible(false);
                            target_pig5.setVisible(false);
                            target_pig6.setVisible(false);
                        }
                        if (i == 19) {
                            target_pig1.setVisible(false);
                            target_pig2.setVisible(false);
                            target_pig3.setVisible(false);
                            target_pig4.setVisible(true);
                            target_pig5.setVisible(false);
                            target_pig6.setVisible(false);
                        }
                        if (i == 21) {
                            target_pig1.setVisible(false);
                            target_pig2.setVisible(false);
                            target_pig3.setVisible(false);
                            target_pig4.setVisible(false);
                            target_pig5.setVisible(true);
                            target_pig6.setVisible(false);
                        }
                        if (i == 23) {
                            target_pig1.setVisible(false);
                            target_pig2.setVisible(false);
                            target_pig3.setVisible(false);
                            target_pig4.setVisible(false);
                            target_pig5.setVisible(false);
                            target_pig6.setVisible(true);
                        }

                        Thread.sleep(thr_val);
                    }
                    targest_animate();

                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }).start();

    }

    private void customCursor() {
        Toolkit tk = Toolkit.getDefaultToolkit();
        Image img = new ImageIcon(getClass().getResource("/images/trg.png")).getImage();
        Point p = new Point(0, 0);
        Cursor c = tk.createCustomCursor(img, p, "Cursor");
        jPanel_background.setCursor(c);

    }

    private void SETico() {
        try {
            setIconImage(ImageIO.read(new BufferedInputStream(getClass().getResourceAsStream("/images/gameic.png"))));

        } catch (IOException ex) {

        }
    }

    private void countdown() {

        new Thread(new Runnable() {

            @Override
            public void run() {
                try {

                    for (int j = 60; j >= 0; j--) {
                        txt_time.setText("Time Remaining " + j);

                        if (j == 0) {

                            Score_panel sp = new Score_panel(null, true);
                            winSound();
                            sp.setVisible(true);

                        }
                        Thread.sleep(1000);
                        String vl = HomePage.lb_thread_stoping_value.getText();
                        if ("1".equals(vl)) {
                            Thread.currentThread().stop();
                        }

                    }
                    Thread.currentThread().stop();

                } catch (InterruptedException e) {
                }

            }
        }).start();
    }

    private void gunclick_sound() {
        try {

            URL url = this.getClass().getResource("/audio/gunclick.wav");
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
            Clip clip = AudioSystem.getClip();
            clip.open(audioIn);
            clip.start();

        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            System.out.println(e);
        }
    }

    private void click_Empty() {
        try {

            URL url = this.getClass().getResource("/audio/emptyclick.wav");
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
            Clip clip = AudioSystem.getClip();
            clip.open(audioIn);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            System.out.println(e);
        }
    }

    private void pig_kill() {
        try {

            URL url = this.getClass().getResource("/audio/pig.wav");
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
            Clip clip = AudioSystem.getClip();
            clip.open(audioIn);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            System.out.println(e);
        }
    }

    private void winSound() {
        try {

            URL url = this.getClass().getResource("/audio/win.wav");
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
            Clip clip = AudioSystem.getClip();
            clip.open(audioIn);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            System.out.println(e);
        }
    }

    private void Window_Closer() {

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent evt) {

                Disp();

            }
        }
        );
    }
}
